from typing import Protocol

from .ai_model import AIModel
from .ai_provider import AIProvider
from .external_login_link import ExternalLoginLink
from .password_credential import PasswordCredential
from .provider_token import ProviderToken
from .user import User
from .usage_event import UsageEvent


class UserRepository(Protocol):
    def get(self, mail: str) -> User | None: ...
    def save(self, user: User) -> User: ...
    def exists(self, mail: str) -> bool: ...


class PasswordCredentialRepository(Protocol):
    def get(self, user_mail: str) -> PasswordCredential | None: ...
    def save(self, credential: PasswordCredential) -> PasswordCredential: ...


class ExternalLoginLinkRepository(Protocol):
    def get_by_subject(self, provider: str, external_subject: str) -> ExternalLoginLink | None: ...
    def save(self, link: ExternalLoginLink) -> ExternalLoginLink: ...


class AIProviderRepository(Protocol):
    def list(self) -> list[AIProvider]: ...
    def get(self, provider_id: str) -> AIProvider | None: ...


class AIModelRepository(Protocol):
    def list_by_provider(self, provider_id: str) -> list[AIModel]: ...


class ProviderTokenRepository(Protocol):
    def get(self, user_mail: str, provider_id: str) -> ProviderToken | None: ...
    def save(self, token: ProviderToken) -> ProviderToken: ...
    def save_secret(self, user_mail: str, provider_id: str, raw_token: str) -> None: ...
    def get_secret(self, user_mail: str, provider_id: str) -> str | None: ...
    def delete(self, user_mail: str, provider_id: str) -> bool: ...
    def list_for_user(self, user_mail: str) -> list[ProviderToken]: ...


class UsageEventRepository(Protocol):
    def record(self, event: UsageEvent) -> UsageEvent: ...
    def list_for_user(self, user_mail: str) -> list[UsageEvent]: ...
