import { test, expect } from '@playwright/test';

test('real local chat: registration, classification, reload, mobile and deletion', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/register');
  await page.getByLabel('Correo electrónico').fill(`qa.${Date.now()}@example.com`);
  await page.getByLabel('Contraseña').fill('ClaveSegura-123');
  await page.getByLabel('Edad').fill('25');
  await page.getByRole('combobox', { name: 'Profesión' }).selectOption('Estudiante');
  await page.getByRole('button', { name: 'Crear cuenta', exact: true }).click();
  await expect(page.getByText(/Cuenta creada para/)).toBeVisible();
  await page.goto('/nuevo-chat');
  await expect(page.getByRole('heading', { name: 'Clasificá tu consulta.' })).toBeVisible();
  await expect(page.locator('.chat-status-dot')).toHaveAttribute('data-ready', 'true');
  await page.screenshot({ path: 'test-results/local-chat-desktop.png', fullPage: true });
  const prompt = '¿Qué es una API REST?';
  await page.getByLabel('Mensaje para BloqIA').fill(prompt);
  await page.getByRole('button', { name: 'Enviar mensaje' }).click();
  await expect(page.getByRole('article', { name: 'Clasificación de BloqIA' })).toHaveCount(1, { timeout: 150000 });
  await expect(page.getByRole('article', { name: 'Clasificación de BloqIA' }).locator('.chat-classification-result')).not.toBeEmpty();
  await expect(page.locator('.chat-classification-result h2').first()).toHaveText('Consulta general');
  const answer = await page.getByRole('article', { name: 'Clasificación de BloqIA' }).locator('.chat-classification-result').innerText();
  await page.screenshot({ path: 'test-results/local-chat-response.png', fullPage: true });
  await page.reload();
  await expect(page.getByRole('article', { name: 'Clasificación de BloqIA' }).locator('.chat-classification-result')).toHaveText(answer, { useInnerText: true });
  await page.getByLabel('Mensaje para BloqIA').fill('¿Debería dejar de tomar mi medicación?');
  await page.getByRole('button', { name: 'Enviar mensaje' }).click();
  await expect(page.getByText(/Revisión humana requerida/)).toBeVisible({ timeout: 30000 });
  await expect(page.locator('.chat-classification-result [data-review]').last()).toHaveText('Revisión humana requerida');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/local-chat-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  const sendBounds = await page.getByRole('button', { name: 'Enviar mensaje' }).boundingBox();
  expect(sendBounds!.y + sendBounds!.height).toBeLessThan(844 - 56);
  await page.getByRole('button', { name: '☰ Historial' }).click();
  await expect(page.getByLabel('Historial de conversaciones')).toBeVisible();
  page.once('dialog', (dialog) => dialog.accept());
  await page.getByRole('button', { name: `Eliminar ${prompt}`, exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Clasificá tu consulta.' })).toBeVisible();
  await page.screenshot({ path: 'test-results/local-chat-mobile-empty.png', fullPage: true });
  expect(errors).toEqual([]);
});
